#!/bin/bash
set -euo pipefail

if command -v starship &>/dev/null; then
  mkdir -p "$HOME/.config"
  starship preset gruvbox-rainbow -o "$HOME/.config/starship.toml"
else
  echo "WARNING: starship not found, skipping starship config. Install it from https://starship.rs"
fi

ghostty_config_dir="$HOME/.config/ghostty"
ghostty_source_dir="$HOME/.dotscripts/ghostty"

if [[ ! -d "$ghostty_source_dir" ]]; then
  echo "WARNING: Ghostty config source not found: $ghostty_source_dir"
else
  mkdir -p "$ghostty_config_dir"
  ghostty_platform_source=""

  case "$(uname -s)" in
    Darwin)
      ghostty_platform_source="$ghostty_source_dir/macos"
      ;;
    Linux)
      ghostty_platform_source="$ghostty_source_dir/linux"
      ;;
    *)
      echo "WARNING: unsupported OS for Ghostty platform config: $(uname -s)"
      ;;
  esac

  if [[ ! -f "$ghostty_source_dir/common" ]]; then
    echo "ERROR: Ghostty common config source not found: $ghostty_source_dir/common"
    exit 1
  fi

  if [[ -n "$ghostty_platform_source" && ! -f "$ghostty_platform_source" ]]; then
    echo "ERROR: Ghostty platform config source not found: $ghostty_platform_source"
    exit 1
  fi

  ghostty_tmp="$(mktemp "$ghostty_config_dir/config.tmp.XXXXXX")"
  {
    echo "# This file is generated by ~/.dotscripts/setup.sh."
    echo "# Edit ~/.dotscripts/ghostty/*, then rerun setup.sh."
    echo
    cat "$ghostty_source_dir/common"
    if [[ -n "$ghostty_platform_source" ]]; then
      cat "$ghostty_platform_source"
    fi
  } >"$ghostty_tmp"

  if [[ -f "$ghostty_config_dir/config" ]] && cmp -s "$ghostty_tmp" "$ghostty_config_dir/config"; then
    rm "$ghostty_tmp"
    echo "Ghostty config unchanged"
  else
    mv "$ghostty_tmp" "$ghostty_config_dir/config"
    echo "Ghostty config updated"
  fi
fi
