#!/bin/bash
set -euo pipefail

generated_header="# This file is generated by ~/.dotscripts/setup.sh."

install_generated_file() {
  local source_file="$1"
  local target_file="$2"
  local label="$3"

  if [[ -f "$target_file" ]] && cmp -s "$source_file" "$target_file"; then
    rm "$source_file"
    echo "$label unchanged"
    return
  fi

  if [[ -f "$target_file" ]]; then
    if ! head -n 1 "$target_file" | grep -Fxq "$generated_header" && diff -q <(tail -n +4 "$source_file") "$target_file" &>/dev/null; then
      mv "$source_file" "$target_file"
      echo "$label updated"
      return
    fi

    if [[ -t 0 ]]; then
      read -r -p "$target_file exists and differs from generated $label. Overwrite? [y/N] " reply
      case "$reply" in
        [yY] | [yY][eE][sS]) ;;
        *)
          rm "$source_file"
          echo "$label skipped"
          return
          ;;
      esac
    else
      rm "$source_file"
      echo "WARNING: $label skipped because $target_file differs from generated output"
      return
    fi
  fi

  mv "$source_file" "$target_file"
  echo "$label updated"
}

if command -v starship &>/dev/null; then
  mkdir -p "$HOME/.config"
  starship_tmp="$(mktemp "$HOME/.config/starship.toml.tmp.XXXXXX")"
  {
    echo "$generated_header"
    echo "# Re-run ~/.dotscripts/setup.sh to refresh the gruvbox-rainbow preset."
    echo
  } >"$starship_tmp"
  starship preset gruvbox-rainbow >>"$starship_tmp"
  install_generated_file "$starship_tmp" "$HOME/.config/starship.toml" "Starship config"
else
  echo "WARNING: starship not found, skipping starship config. Install it from https://starship.rs"
fi

ghostty_config_dir="$HOME/.config/ghostty"
ghostty_source_dir="$HOME/.dotscripts/ghostty"

if [[ ! -d "$ghostty_source_dir" ]]; then
  echo "WARNING: Ghostty config source not found: $ghostty_source_dir"
else
  mkdir -p "$ghostty_config_dir"
  ghostty_platform_source=""

  case "$(uname -s)" in
    Darwin)
      ghostty_platform_source="$ghostty_source_dir/macos"
      ;;
    Linux)
      ghostty_platform_source="$ghostty_source_dir/linux"
      ;;
    *)
      echo "WARNING: unsupported OS for Ghostty platform config: $(uname -s)"
      ;;
  esac

  if [[ ! -f "$ghostty_source_dir/common" ]]; then
    echo "ERROR: Ghostty common config source not found: $ghostty_source_dir/common"
    exit 1
  fi

  if [[ -n "$ghostty_platform_source" && ! -f "$ghostty_platform_source" ]]; then
    echo "ERROR: Ghostty platform config source not found: $ghostty_platform_source"
    exit 1
  fi

  ghostty_tmp="$(mktemp "$ghostty_config_dir/config.tmp.XXXXXX")"
  {
    echo "$generated_header"
    echo "# Edit ~/.dotscripts/ghostty/*, then rerun setup.sh."
    echo
    cat "$ghostty_source_dir/common"
    if [[ -n "$ghostty_platform_source" ]]; then
      cat "$ghostty_platform_source"
    fi
  } >"$ghostty_tmp"
  install_generated_file "$ghostty_tmp" "$ghostty_config_dir/config" "Ghostty config"
fi
