-- ===== Autocommands =====
-- Add your own autocommands here, e.g. highlight on yank:
--   vim.api.nvim_create_autocmd("TextYankPost", {
--     callback = function() vim.highlight.on_yank() end,
--   })
